export const reducerCases = {
    SET_SEARCHKEY: "SET_SEARCHKEY",
    SET_LOADING: "SET_LOADING",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SET_TOKEN: "SET_TOKEN",
    SET_MESSAGES: "SET_MESSAGES",
    SET_USERS: "SET_USERS",
    SET_LOADER: "SET_LOADER",
    SET_SELECTED_USER: "SET_SELECTED_USER",
    SET_CONVERSATION: "SET_CONVERSATION",
}